### ISSUE TITLE
 Can angular material 19 be supported?

### ISSUE THREAD

**Issue by Izimbergenov** [h2qutc/angular-material-components#404]
Can angular material 19 be supported?

**Comment by h2qutc** [comment]
@Izimbergenov  Yes, we will release a new version supporting Angular 18/19.

**Comment by elirov** [comment]
Any idea what kind of timeline we're looking at? Thank you!

**Comment by Burgov** [comment]
Would like to migrate to ng19 too, but blocked by this libary

**Comment by Izimbergenov** [comment]
@Burgov the same problem

**Comment by oemergenc** [comment]
@h2qutc any ETA? same problem here

**Comment by ricardoduarte** [comment]
+1 for this feature

**Comment by anschm** [comment]
@h2qutc any ETA?

**Comment by jayyanez** [comment]
This library is the only thing preventing me from upgrading to Angular 19. I noticed that your last update was over a year ago. If you no longer plan to maintain this library, could you please let us know? This would help us decide whether to look for an alternative instead of waiting indefinitely for an update.

**Comment by faraz-ahmad-uft** [comment]
@h2qutc - Please let me know when you are doing migration to v19. I need to migrate multiple projects to v19 and all my projects are using this library. I am stuck due to older version of this library. Thanks

**Comment by Luiz-Otavio-Dorigon** [comment]
Any idea when this lib will be updated to v19? I need to update my projects and I'm stuck because of this lib.

**Comment by faraz-ahmad-uft** [comment]
Following library can be used if support is not provided by the author.

https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker

**Comment by Luiz-Otavio-Dorigon** [comment]
@faraz-ahmad-uft This lib does not have a color-picker or file-input so it cannot be used to replace

**Comment by faraz-ahmad-uft** [comment]
@Luiz-Otavio-Dorigon -  I require a date time picker only so it worked in my case. Have you migrated to the latest version?

**Comment by ironista** [comment]
I appreciate your support, but I had to migrate to a fork of this project: [GNURub/angular-material-components](https://github.com/GNURub/angular-material-components).

**Comment by danoscosmos** [comment]
> I appreciate your support, but I had to migrate to a fork of this project: [GNURub/angular-material-components](https://github.com/GNURub/angular-material-components).

Are you using the datetimepicker component? The NgxMatDatetimePickerModule module does not exist in the fork

**Comment by ironista** [comment]
I'm using standalone component [NgxMatDatetimepicker](https://github.com/GNURub/angular-material-components/blob/main/projects/datetime-picker/src/lib/datepicker.ts).

**Comment by nakurd** [comment]
@h2qutc can we please get an ETA?

**Comment by Izimbergenov** [comment]
@h2qutc  any news?

**Comment by Izimbergenov** [comment]
@h2qutc any news?

**Comment by GNURub** [comment]
@Izimbergenov you can use the fork: https://www.npmjs.com/package/@ngxmc/datetime-picker?activeTab=readme read the doc for migrate.

**Comment by serg-mois-capital** [comment]
@GNURub after update from 19.1 to 19.3 - there are errors,
NgxMatNativeDateModule, NgxMatNativeDateAdapter, NgxMatDateFormats - are not exported anymore from @ngxmc/datetime-picker

**Comment by GNURub** [comment]
@serg-mois-capital  check docs: https://www.npmjs.com/package/@ngxmc/datetime-picker?activeTab=readme now is using material providers and formats

**Comment by saurabh230197** [comment]
@GNURub I imported NgxMatDatetimepicker from @ngxmc/datetime-picker in my component but I'm still getting error: 'ngx-mat-datetime-picker' is not a known element. I'm using @ngxmc/datetime-picker version 19.1

**Comment by serg-mois-capital** [comment]
> [@serg-mois-capital](https://github.com/serg-mois-capital) check docs: https://www.npmjs.com/package/@ngxmc/datetime-picker?activeTab=readme now is using material providers and formats

@GNURub after switching from NgxMatNativeDateAdapter to NativeDateAdapter

`export class CustomDateTimeAdapter extends NativeDateAdapter `

I'm getting error on opening datetimepicker:

```
TypeError: Cannot read properties of undefined (reading 'getHours')
    at CustomDateTimeAdapter.getHours (core.mjs:537:17)
    at _NgxMatTimepickerComponent._updateHourMinuteSecond (ngxmc-datetime-picker.mjs:4795:35)
```


Also, after changing the time in opened "calendar dialog" at the bottom and closing thy dialog I got

```
reportUnhandledError.js:9 Uncaught RuntimeError: NG0953: Unexpected emit for destroyed `OutputRef`. The owning directive/component is destroyed.
    at OutputEmitterRef.emit (core.mjs:6736:13)
    at getter.set (core.mjs:18543:18)
    at _NgxMatTimepickerComponent._updateModel (ngxmc-datetime-picker.mjs:4834:18)
```

**Comment by GNURub** [comment]
@serg-mois-capital  https://stackblitz.com/edit/bgwkmexc?file=package.json,src%2Fexample%2Fdatepicker-locale-example.html,src%2Fexample%2Fdatepicker-locale-example.ts,src%2Fmain.ts,src%2Fexample%2Fdatepicker-locale-example.css

**Comment by serg-mois-capital** [comment]
@GNURub see picker at the bottom:
 https://stackblitz.com/~/github.com/dkastsianok/datepicker?file=src/app/app.component.html


![Image](https://github.com/user-attachments/assets/55bd11b3-1238-45de-8d10-8fbc5a964517)

![Image](https://github.com/user-attachments/assets/71732db6-20bb-49df-8d05-816540da8f6a)

**Comment by serg-mois-capital** [comment]
@GNURub in 19.3.1. first exception has been fixed. Thank you very much.

But the second one is still relevant:

```
 reportUnhandledError.js:9 Uncaught RuntimeError: NG0953: Unexpected emit for destroyed `OutputRef`. The owning directive/component is destroyed.
    at OutputEmitterRef.emit (core.mjs:6736:13)
    at getter.set (core.mjs:18543:18)
    at _NgxMatTimepickerComponent._updateModel (ngxmc-datetime-picker.mjs:4836:18)
```

**Comment by taher-samman** [comment]
@h2qutc when will the compatible version with angular 19 be ready?

**Comment by SikFar** [comment]
If you are using Angular Material, they introduced Timepicker, which can be combined with datepicker, see [here](https://v19.material.angular.dev/components/timepicker/examples#timepicker-datepicker-integration)

2 years since last commit is not dependable, deleted @angular-material-components
